apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dso-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dso-demo
  template:
    metadata:
      labels:
        app: dso-demo
    spec:
      containers:
        - name: dso-demo
          image: fdjapi10/dsodemo:latest
            - containerPort: 9000
          volumeMounts:
            - name: demo-extensions
              mountPath: /opt/sonarqube/extensions
      volumes:
        - name: demo-extensions
          persistentVolumeClaim:
            claimName: demo-pvc

