apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: dso-demo
  name: dso-demo-svc
spec:
  ports:
  - name: "9000"
    nodePort: 30080
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: dso-demo
  type: NodePort
